name: practica

on:
 push:
  branches: [main]

jobs:
  miPrimerJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mi primera action"
      - run: date
      - run: ls -l
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
   